//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomia.SRNegocio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringBuilder", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StringBuilder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CapacityField;
        
        private int LengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRNegocio.NegociosSoap")]
    public interface NegociosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuerpoCeleste", ReplyAction="*")]
        Astronomia.SRNegocio.CuerpoCelesteResponse CuerpoCeleste(Astronomia.SRNegocio.CuerpoCelesteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuerpoCeleste", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.CuerpoCelesteResponse> CuerpoCelesteAsync(Astronomia.SRNegocio.CuerpoCelesteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asociarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/asociar", ReplyAction="*")]
        Astronomia.SRNegocio.asociarResponse asociar(Astronomia.SRNegocio.asociarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/asociar", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.asociarResponse> asociarAsync(Astronomia.SRNegocio.asociarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTipo", ReplyAction="*")]
        Astronomia.SRNegocio.insertarTipoResponse insertarTipo(Astronomia.SRNegocio.insertarTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.insertarTipoResponse> insertarTipoAsync(Astronomia.SRNegocio.insertarTipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultarTipoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTipo", ReplyAction="*")]
        Astronomia.SRNegocio.consultarTipoResponse consultarTipo(Astronomia.SRNegocio.consultarTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.consultarTipoResponse> consultarTipoAsync(Astronomia.SRNegocio.consultarTipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultarCuerpoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarCuerpo", ReplyAction="*")]
        Astronomia.SRNegocio.consultarCuerpoResponse consultarCuerpo(Astronomia.SRNegocio.consultarCuerpoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarCuerpo", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.consultarCuerpoResponse> consultarCuerpoAsync(Astronomia.SRNegocio.consultarCuerpoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento crearTablaTiposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearTablaTipos", ReplyAction="*")]
        Astronomia.SRNegocio.crearTablaTiposResponse crearTablaTipos(Astronomia.SRNegocio.crearTablaTiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearTablaTipos", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.crearTablaTiposResponse> crearTablaTiposAsync(Astronomia.SRNegocio.crearTablaTiposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento crearTablaCuerposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearTablaCuerpos", ReplyAction="*")]
        Astronomia.SRNegocio.crearTablaCuerposResponse crearTablaCuerpos(Astronomia.SRNegocio.crearTablaCuerposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearTablaCuerpos", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.crearTablaCuerposResponse> crearTablaCuerposAsync(Astronomia.SRNegocio.crearTablaCuerposRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuerpoCelesteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuerpoCeleste", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.CuerpoCelesteRequestBody Body;
        
        public CuerpoCelesteRequest() {
        }
        
        public CuerpoCelesteRequest(Astronomia.SRNegocio.CuerpoCelesteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuerpoCelesteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descubridor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string archivos;
        
        public CuerpoCelesteRequestBody() {
        }
        
        public CuerpoCelesteRequestBody(string nombre, string descubridor, string archivos) {
            this.nombre = nombre;
            this.descubridor = descubridor;
            this.archivos = archivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuerpoCelesteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuerpoCelesteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.CuerpoCelesteResponseBody Body;
        
        public CuerpoCelesteResponse() {
        }
        
        public CuerpoCelesteResponse(Astronomia.SRNegocio.CuerpoCelesteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuerpoCelesteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CuerpoCelesteResult;
        
        public CuerpoCelesteResponseBody() {
        }
        
        public CuerpoCelesteResponseBody(string CuerpoCelesteResult) {
            this.CuerpoCelesteResult = CuerpoCelesteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class asociarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="asociar", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.asociarRequestBody Body;
        
        public asociarRequest() {
        }
        
        public asociarRequest(Astronomia.SRNegocio.asociarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class asociarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCuerpo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idAsociado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idTipo;
        
        public asociarRequestBody() {
        }
        
        public asociarRequestBody(int idCuerpo, int idAsociado, int idTipo) {
            this.idCuerpo = idCuerpo;
            this.idAsociado = idAsociado;
            this.idTipo = idTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class asociarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="asociarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.asociarResponseBody Body;
        
        public asociarResponse() {
        }
        
        public asociarResponse(Astronomia.SRNegocio.asociarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class asociarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asociarResult;
        
        public asociarResponseBody() {
        }
        
        public asociarResponseBody(string asociarResult) {
            this.asociarResult = asociarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTipo", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.insertarTipoRequestBody Body;
        
        public insertarTipoRequest() {
        }
        
        public insertarTipoRequest(Astronomia.SRNegocio.insertarTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        public insertarTipoRequestBody() {
        }
        
        public insertarTipoRequestBody(string descripcion) {
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.insertarTipoResponseBody Body;
        
        public insertarTipoResponse() {
        }
        
        public insertarTipoResponse(Astronomia.SRNegocio.insertarTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertarTipoResult;
        
        public insertarTipoResponseBody() {
        }
        
        public insertarTipoResponseBody(string insertarTipoResult) {
            this.insertarTipoResult = insertarTipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarTipo", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.consultarTipoRequestBody Body;
        
        public consultarTipoRequest() {
        }
        
        public consultarTipoRequest(Astronomia.SRNegocio.consultarTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarTipoRequestBody {
        
        public consultarTipoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.consultarTipoResponseBody Body;
        
        public consultarTipoResponse() {
        }
        
        public consultarTipoResponse(Astronomia.SRNegocio.consultarTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarTipoResult;
        
        public consultarTipoResponseBody() {
        }
        
        public consultarTipoResponseBody(string consultarTipoResult) {
            this.consultarTipoResult = consultarTipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarCuerpoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarCuerpo", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.consultarCuerpoRequestBody Body;
        
        public consultarCuerpoRequest() {
        }
        
        public consultarCuerpoRequest(Astronomia.SRNegocio.consultarCuerpoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarCuerpoRequestBody {
        
        public consultarCuerpoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarCuerpoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarCuerpoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.consultarCuerpoResponseBody Body;
        
        public consultarCuerpoResponse() {
        }
        
        public consultarCuerpoResponse(Astronomia.SRNegocio.consultarCuerpoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarCuerpoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarCuerpoResult;
        
        public consultarCuerpoResponseBody() {
        }
        
        public consultarCuerpoResponseBody(string consultarCuerpoResult) {
            this.consultarCuerpoResult = consultarCuerpoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearTablaTiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearTablaTipos", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.crearTablaTiposRequestBody Body;
        
        public crearTablaTiposRequest() {
        }
        
        public crearTablaTiposRequest(Astronomia.SRNegocio.crearTablaTiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class crearTablaTiposRequestBody {
        
        public crearTablaTiposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearTablaTiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearTablaTiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.crearTablaTiposResponseBody Body;
        
        public crearTablaTiposResponse() {
        }
        
        public crearTablaTiposResponse(Astronomia.SRNegocio.crearTablaTiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crearTablaTiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Astronomia.SRNegocio.StringBuilder crearTablaTiposResult;
        
        public crearTablaTiposResponseBody() {
        }
        
        public crearTablaTiposResponseBody(Astronomia.SRNegocio.StringBuilder crearTablaTiposResult) {
            this.crearTablaTiposResult = crearTablaTiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearTablaCuerposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearTablaCuerpos", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.crearTablaCuerposRequestBody Body;
        
        public crearTablaCuerposRequest() {
        }
        
        public crearTablaCuerposRequest(Astronomia.SRNegocio.crearTablaCuerposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class crearTablaCuerposRequestBody {
        
        public crearTablaCuerposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearTablaCuerposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearTablaCuerposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.crearTablaCuerposResponseBody Body;
        
        public crearTablaCuerposResponse() {
        }
        
        public crearTablaCuerposResponse(Astronomia.SRNegocio.crearTablaCuerposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crearTablaCuerposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Astronomia.SRNegocio.StringBuilder crearTablaCuerposResult;
        
        public crearTablaCuerposResponseBody() {
        }
        
        public crearTablaCuerposResponseBody(Astronomia.SRNegocio.StringBuilder crearTablaCuerposResult) {
            this.crearTablaCuerposResult = crearTablaCuerposResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NegociosSoapChannel : Astronomia.SRNegocio.NegociosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NegociosSoapClient : System.ServiceModel.ClientBase<Astronomia.SRNegocio.NegociosSoap>, Astronomia.SRNegocio.NegociosSoap {
        
        public NegociosSoapClient() {
        }
        
        public NegociosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NegociosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.CuerpoCelesteResponse Astronomia.SRNegocio.NegociosSoap.CuerpoCeleste(Astronomia.SRNegocio.CuerpoCelesteRequest request) {
            return base.Channel.CuerpoCeleste(request);
        }
        
        public string CuerpoCeleste(string nombre, string descubridor, string archivos) {
            Astronomia.SRNegocio.CuerpoCelesteRequest inValue = new Astronomia.SRNegocio.CuerpoCelesteRequest();
            inValue.Body = new Astronomia.SRNegocio.CuerpoCelesteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descubridor = descubridor;
            inValue.Body.archivos = archivos;
            Astronomia.SRNegocio.CuerpoCelesteResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).CuerpoCeleste(inValue);
            return retVal.Body.CuerpoCelesteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.CuerpoCelesteResponse> Astronomia.SRNegocio.NegociosSoap.CuerpoCelesteAsync(Astronomia.SRNegocio.CuerpoCelesteRequest request) {
            return base.Channel.CuerpoCelesteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.CuerpoCelesteResponse> CuerpoCelesteAsync(string nombre, string descubridor, string archivos) {
            Astronomia.SRNegocio.CuerpoCelesteRequest inValue = new Astronomia.SRNegocio.CuerpoCelesteRequest();
            inValue.Body = new Astronomia.SRNegocio.CuerpoCelesteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descubridor = descubridor;
            inValue.Body.archivos = archivos;
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).CuerpoCelesteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.asociarResponse Astronomia.SRNegocio.NegociosSoap.asociar(Astronomia.SRNegocio.asociarRequest request) {
            return base.Channel.asociar(request);
        }
        
        public string asociar(int idCuerpo, int idAsociado, int idTipo) {
            Astronomia.SRNegocio.asociarRequest inValue = new Astronomia.SRNegocio.asociarRequest();
            inValue.Body = new Astronomia.SRNegocio.asociarRequestBody();
            inValue.Body.idCuerpo = idCuerpo;
            inValue.Body.idAsociado = idAsociado;
            inValue.Body.idTipo = idTipo;
            Astronomia.SRNegocio.asociarResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).asociar(inValue);
            return retVal.Body.asociarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.asociarResponse> Astronomia.SRNegocio.NegociosSoap.asociarAsync(Astronomia.SRNegocio.asociarRequest request) {
            return base.Channel.asociarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.asociarResponse> asociarAsync(int idCuerpo, int idAsociado, int idTipo) {
            Astronomia.SRNegocio.asociarRequest inValue = new Astronomia.SRNegocio.asociarRequest();
            inValue.Body = new Astronomia.SRNegocio.asociarRequestBody();
            inValue.Body.idCuerpo = idCuerpo;
            inValue.Body.idAsociado = idAsociado;
            inValue.Body.idTipo = idTipo;
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).asociarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.insertarTipoResponse Astronomia.SRNegocio.NegociosSoap.insertarTipo(Astronomia.SRNegocio.insertarTipoRequest request) {
            return base.Channel.insertarTipo(request);
        }
        
        public string insertarTipo(string descripcion) {
            Astronomia.SRNegocio.insertarTipoRequest inValue = new Astronomia.SRNegocio.insertarTipoRequest();
            inValue.Body = new Astronomia.SRNegocio.insertarTipoRequestBody();
            inValue.Body.descripcion = descripcion;
            Astronomia.SRNegocio.insertarTipoResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).insertarTipo(inValue);
            return retVal.Body.insertarTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.insertarTipoResponse> Astronomia.SRNegocio.NegociosSoap.insertarTipoAsync(Astronomia.SRNegocio.insertarTipoRequest request) {
            return base.Channel.insertarTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.insertarTipoResponse> insertarTipoAsync(string descripcion) {
            Astronomia.SRNegocio.insertarTipoRequest inValue = new Astronomia.SRNegocio.insertarTipoRequest();
            inValue.Body = new Astronomia.SRNegocio.insertarTipoRequestBody();
            inValue.Body.descripcion = descripcion;
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).insertarTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.consultarTipoResponse Astronomia.SRNegocio.NegociosSoap.consultarTipo(Astronomia.SRNegocio.consultarTipoRequest request) {
            return base.Channel.consultarTipo(request);
        }
        
        public string consultarTipo() {
            Astronomia.SRNegocio.consultarTipoRequest inValue = new Astronomia.SRNegocio.consultarTipoRequest();
            inValue.Body = new Astronomia.SRNegocio.consultarTipoRequestBody();
            Astronomia.SRNegocio.consultarTipoResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).consultarTipo(inValue);
            return retVal.Body.consultarTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.consultarTipoResponse> Astronomia.SRNegocio.NegociosSoap.consultarTipoAsync(Astronomia.SRNegocio.consultarTipoRequest request) {
            return base.Channel.consultarTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.consultarTipoResponse> consultarTipoAsync() {
            Astronomia.SRNegocio.consultarTipoRequest inValue = new Astronomia.SRNegocio.consultarTipoRequest();
            inValue.Body = new Astronomia.SRNegocio.consultarTipoRequestBody();
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).consultarTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.consultarCuerpoResponse Astronomia.SRNegocio.NegociosSoap.consultarCuerpo(Astronomia.SRNegocio.consultarCuerpoRequest request) {
            return base.Channel.consultarCuerpo(request);
        }
        
        public string consultarCuerpo() {
            Astronomia.SRNegocio.consultarCuerpoRequest inValue = new Astronomia.SRNegocio.consultarCuerpoRequest();
            inValue.Body = new Astronomia.SRNegocio.consultarCuerpoRequestBody();
            Astronomia.SRNegocio.consultarCuerpoResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).consultarCuerpo(inValue);
            return retVal.Body.consultarCuerpoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.consultarCuerpoResponse> Astronomia.SRNegocio.NegociosSoap.consultarCuerpoAsync(Astronomia.SRNegocio.consultarCuerpoRequest request) {
            return base.Channel.consultarCuerpoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.consultarCuerpoResponse> consultarCuerpoAsync() {
            Astronomia.SRNegocio.consultarCuerpoRequest inValue = new Astronomia.SRNegocio.consultarCuerpoRequest();
            inValue.Body = new Astronomia.SRNegocio.consultarCuerpoRequestBody();
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).consultarCuerpoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.crearTablaTiposResponse Astronomia.SRNegocio.NegociosSoap.crearTablaTipos(Astronomia.SRNegocio.crearTablaTiposRequest request) {
            return base.Channel.crearTablaTipos(request);
        }
        
        public Astronomia.SRNegocio.StringBuilder crearTablaTipos() {
            Astronomia.SRNegocio.crearTablaTiposRequest inValue = new Astronomia.SRNegocio.crearTablaTiposRequest();
            inValue.Body = new Astronomia.SRNegocio.crearTablaTiposRequestBody();
            Astronomia.SRNegocio.crearTablaTiposResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).crearTablaTipos(inValue);
            return retVal.Body.crearTablaTiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.crearTablaTiposResponse> Astronomia.SRNegocio.NegociosSoap.crearTablaTiposAsync(Astronomia.SRNegocio.crearTablaTiposRequest request) {
            return base.Channel.crearTablaTiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.crearTablaTiposResponse> crearTablaTiposAsync() {
            Astronomia.SRNegocio.crearTablaTiposRequest inValue = new Astronomia.SRNegocio.crearTablaTiposRequest();
            inValue.Body = new Astronomia.SRNegocio.crearTablaTiposRequestBody();
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).crearTablaTiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.crearTablaCuerposResponse Astronomia.SRNegocio.NegociosSoap.crearTablaCuerpos(Astronomia.SRNegocio.crearTablaCuerposRequest request) {
            return base.Channel.crearTablaCuerpos(request);
        }
        
        public Astronomia.SRNegocio.StringBuilder crearTablaCuerpos() {
            Astronomia.SRNegocio.crearTablaCuerposRequest inValue = new Astronomia.SRNegocio.crearTablaCuerposRequest();
            inValue.Body = new Astronomia.SRNegocio.crearTablaCuerposRequestBody();
            Astronomia.SRNegocio.crearTablaCuerposResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).crearTablaCuerpos(inValue);
            return retVal.Body.crearTablaCuerposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.crearTablaCuerposResponse> Astronomia.SRNegocio.NegociosSoap.crearTablaCuerposAsync(Astronomia.SRNegocio.crearTablaCuerposRequest request) {
            return base.Channel.crearTablaCuerposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.crearTablaCuerposResponse> crearTablaCuerposAsync() {
            Astronomia.SRNegocio.crearTablaCuerposRequest inValue = new Astronomia.SRNegocio.crearTablaCuerposRequest();
            inValue.Body = new Astronomia.SRNegocio.crearTablaCuerposRequestBody();
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).crearTablaCuerposAsync(inValue);
        }
    }
}
