//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomia.SRNegocio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRNegocio.NegociosSoap")]
    public interface NegociosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Astronomia.SRNegocio.HelloWorldResponse HelloWorld(Astronomia.SRNegocio.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.HelloWorldResponse> HelloWorldAsync(Astronomia.SRNegocio.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuerpoCeleste", ReplyAction="*")]
        Astronomia.SRNegocio.CuerpoCelesteResponse CuerpoCeleste(Astronomia.SRNegocio.CuerpoCelesteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuerpoCeleste", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.CuerpoCelesteResponse> CuerpoCelesteAsync(Astronomia.SRNegocio.CuerpoCelesteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asociarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/asociar", ReplyAction="*")]
        Astronomia.SRNegocio.asociarResponse asociar(Astronomia.SRNegocio.asociarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/asociar", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.asociarResponse> asociarAsync(Astronomia.SRNegocio.asociarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTipo", ReplyAction="*")]
        Astronomia.SRNegocio.insertarTipoResponse insertarTipo(Astronomia.SRNegocio.insertarTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.insertarTipoResponse> insertarTipoAsync(Astronomia.SRNegocio.insertarTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getConsultarTipo", ReplyAction="*")]
        void getConsultarTipo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getConsultarTipo", ReplyAction="*")]
        System.Threading.Tasks.Task getConsultarTipoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCuerpos", ReplyAction="*")]
        void getCuerpos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCuerpos", ReplyAction="*")]
        System.Threading.Tasks.Task getCuerposAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Astronomia.SRNegocio.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Astronomia.SRNegocio.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuerpoCelesteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuerpoCeleste", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.CuerpoCelesteRequestBody Body;
        
        public CuerpoCelesteRequest() {
        }
        
        public CuerpoCelesteRequest(Astronomia.SRNegocio.CuerpoCelesteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuerpoCelesteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descubridor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string archivos;
        
        public CuerpoCelesteRequestBody() {
        }
        
        public CuerpoCelesteRequestBody(string nombre, string descubridor, string archivos) {
            this.nombre = nombre;
            this.descubridor = descubridor;
            this.archivos = archivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuerpoCelesteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuerpoCelesteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.CuerpoCelesteResponseBody Body;
        
        public CuerpoCelesteResponse() {
        }
        
        public CuerpoCelesteResponse(Astronomia.SRNegocio.CuerpoCelesteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuerpoCelesteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CuerpoCelesteResult;
        
        public CuerpoCelesteResponseBody() {
        }
        
        public CuerpoCelesteResponseBody(string CuerpoCelesteResult) {
            this.CuerpoCelesteResult = CuerpoCelesteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class asociarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="asociar", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.asociarRequestBody Body;
        
        public asociarRequest() {
        }
        
        public asociarRequest(Astronomia.SRNegocio.asociarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class asociarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCuerpo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idAsociado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idTipo;
        
        public asociarRequestBody() {
        }
        
        public asociarRequestBody(int idCuerpo, int idAsociado, int idTipo) {
            this.idCuerpo = idCuerpo;
            this.idAsociado = idAsociado;
            this.idTipo = idTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class asociarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="asociarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.asociarResponseBody Body;
        
        public asociarResponse() {
        }
        
        public asociarResponse(Astronomia.SRNegocio.asociarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class asociarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asociarResult;
        
        public asociarResponseBody() {
        }
        
        public asociarResponseBody(string asociarResult) {
            this.asociarResult = asociarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTipo", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.insertarTipoRequestBody Body;
        
        public insertarTipoRequest() {
        }
        
        public insertarTipoRequest(Astronomia.SRNegocio.insertarTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        public insertarTipoRequestBody() {
        }
        
        public insertarTipoRequestBody(string descripcion) {
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRNegocio.insertarTipoResponseBody Body;
        
        public insertarTipoResponse() {
        }
        
        public insertarTipoResponse(Astronomia.SRNegocio.insertarTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertarTipoResult;
        
        public insertarTipoResponseBody() {
        }
        
        public insertarTipoResponseBody(string insertarTipoResult) {
            this.insertarTipoResult = insertarTipoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NegociosSoapChannel : Astronomia.SRNegocio.NegociosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NegociosSoapClient : System.ServiceModel.ClientBase<Astronomia.SRNegocio.NegociosSoap>, Astronomia.SRNegocio.NegociosSoap {
        
        public NegociosSoapClient() {
        }
        
        public NegociosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NegociosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.HelloWorldResponse Astronomia.SRNegocio.NegociosSoap.HelloWorld(Astronomia.SRNegocio.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Astronomia.SRNegocio.HelloWorldRequest inValue = new Astronomia.SRNegocio.HelloWorldRequest();
            inValue.Body = new Astronomia.SRNegocio.HelloWorldRequestBody();
            Astronomia.SRNegocio.HelloWorldResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.HelloWorldResponse> Astronomia.SRNegocio.NegociosSoap.HelloWorldAsync(Astronomia.SRNegocio.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.HelloWorldResponse> HelloWorldAsync() {
            Astronomia.SRNegocio.HelloWorldRequest inValue = new Astronomia.SRNegocio.HelloWorldRequest();
            inValue.Body = new Astronomia.SRNegocio.HelloWorldRequestBody();
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.CuerpoCelesteResponse Astronomia.SRNegocio.NegociosSoap.CuerpoCeleste(Astronomia.SRNegocio.CuerpoCelesteRequest request) {
            return base.Channel.CuerpoCeleste(request);
        }
        
        public string CuerpoCeleste(string nombre, string descubridor, string archivos) {
            Astronomia.SRNegocio.CuerpoCelesteRequest inValue = new Astronomia.SRNegocio.CuerpoCelesteRequest();
            inValue.Body = new Astronomia.SRNegocio.CuerpoCelesteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descubridor = descubridor;
            inValue.Body.archivos = archivos;
            Astronomia.SRNegocio.CuerpoCelesteResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).CuerpoCeleste(inValue);
            return retVal.Body.CuerpoCelesteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.CuerpoCelesteResponse> Astronomia.SRNegocio.NegociosSoap.CuerpoCelesteAsync(Astronomia.SRNegocio.CuerpoCelesteRequest request) {
            return base.Channel.CuerpoCelesteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.CuerpoCelesteResponse> CuerpoCelesteAsync(string nombre, string descubridor, string archivos) {
            Astronomia.SRNegocio.CuerpoCelesteRequest inValue = new Astronomia.SRNegocio.CuerpoCelesteRequest();
            inValue.Body = new Astronomia.SRNegocio.CuerpoCelesteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descubridor = descubridor;
            inValue.Body.archivos = archivos;
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).CuerpoCelesteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.asociarResponse Astronomia.SRNegocio.NegociosSoap.asociar(Astronomia.SRNegocio.asociarRequest request) {
            return base.Channel.asociar(request);
        }
        
        public string asociar(int idCuerpo, int idAsociado, int idTipo) {
            Astronomia.SRNegocio.asociarRequest inValue = new Astronomia.SRNegocio.asociarRequest();
            inValue.Body = new Astronomia.SRNegocio.asociarRequestBody();
            inValue.Body.idCuerpo = idCuerpo;
            inValue.Body.idAsociado = idAsociado;
            inValue.Body.idTipo = idTipo;
            Astronomia.SRNegocio.asociarResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).asociar(inValue);
            return retVal.Body.asociarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.asociarResponse> Astronomia.SRNegocio.NegociosSoap.asociarAsync(Astronomia.SRNegocio.asociarRequest request) {
            return base.Channel.asociarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.asociarResponse> asociarAsync(int idCuerpo, int idAsociado, int idTipo) {
            Astronomia.SRNegocio.asociarRequest inValue = new Astronomia.SRNegocio.asociarRequest();
            inValue.Body = new Astronomia.SRNegocio.asociarRequestBody();
            inValue.Body.idCuerpo = idCuerpo;
            inValue.Body.idAsociado = idAsociado;
            inValue.Body.idTipo = idTipo;
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).asociarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRNegocio.insertarTipoResponse Astronomia.SRNegocio.NegociosSoap.insertarTipo(Astronomia.SRNegocio.insertarTipoRequest request) {
            return base.Channel.insertarTipo(request);
        }
        
        public string insertarTipo(string descripcion) {
            Astronomia.SRNegocio.insertarTipoRequest inValue = new Astronomia.SRNegocio.insertarTipoRequest();
            inValue.Body = new Astronomia.SRNegocio.insertarTipoRequestBody();
            inValue.Body.descripcion = descripcion;
            Astronomia.SRNegocio.insertarTipoResponse retVal = ((Astronomia.SRNegocio.NegociosSoap)(this)).insertarTipo(inValue);
            return retVal.Body.insertarTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRNegocio.insertarTipoResponse> Astronomia.SRNegocio.NegociosSoap.insertarTipoAsync(Astronomia.SRNegocio.insertarTipoRequest request) {
            return base.Channel.insertarTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRNegocio.insertarTipoResponse> insertarTipoAsync(string descripcion) {
            Astronomia.SRNegocio.insertarTipoRequest inValue = new Astronomia.SRNegocio.insertarTipoRequest();
            inValue.Body = new Astronomia.SRNegocio.insertarTipoRequestBody();
            inValue.Body.descripcion = descripcion;
            return ((Astronomia.SRNegocio.NegociosSoap)(this)).insertarTipoAsync(inValue);
        }
        
        public void getConsultarTipo() {
            base.Channel.getConsultarTipo();
        }
        
        public System.Threading.Tasks.Task getConsultarTipoAsync() {
            return base.Channel.getConsultarTipoAsync();
        }
        
        public void getCuerpos() {
            base.Channel.getCuerpos();
        }
        
        public System.Threading.Tasks.Task getCuerposAsync() {
            return base.Channel.getCuerposAsync();
        }
    }
}
