//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomia.SRBaseDatos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRBaseDatos.BaseDatosSoap")]
    public interface BaseDatosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Astronomia.SRBaseDatos.HelloWorldResponse HelloWorld(Astronomia.SRBaseDatos.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.HelloWorldResponse> HelloWorldAsync(Astronomia.SRBaseDatos.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCuerpo", ReplyAction="*")]
        Astronomia.SRBaseDatos.InsertarCuerpoResponse InsertarCuerpo(Astronomia.SRBaseDatos.InsertarCuerpoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCuerpo", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.InsertarCuerpoResponse> InsertarCuerpoAsync(Astronomia.SRBaseDatos.InsertarCuerpoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTipo", ReplyAction="*")]
        Astronomia.SRBaseDatos.insertarTipoResponse insertarTipo(Astronomia.SRBaseDatos.insertarTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.insertarTipoResponse> insertarTipoAsync(Astronomia.SRBaseDatos.insertarTipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultaCuerposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCuerpos", ReplyAction="*")]
        Astronomia.SRBaseDatos.ConsultaCuerposResponse ConsultaCuerpos(Astronomia.SRBaseDatos.ConsultaCuerposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCuerpos", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.ConsultaCuerposResponse> ConsultaCuerposAsync(Astronomia.SRBaseDatos.ConsultaCuerposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultarTiposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTipos", ReplyAction="*")]
        Astronomia.SRBaseDatos.consultarTiposResponse consultarTipos(Astronomia.SRBaseDatos.consultarTiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTipos", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.consultarTiposResponse> consultarTiposAsync(Astronomia.SRBaseDatos.consultarTiposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento InsertarAsociadosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarAsociados", ReplyAction="*")]
        Astronomia.SRBaseDatos.InsertarAsociadosResponse InsertarAsociados(Astronomia.SRBaseDatos.InsertarAsociadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarAsociados", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.InsertarAsociadosResponse> InsertarAsociadosAsync(Astronomia.SRBaseDatos.InsertarAsociadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultarTotalCuerposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTotalCuerpos", ReplyAction="*")]
        Astronomia.SRBaseDatos.consultarTotalCuerposResponse consultarTotalCuerpos(Astronomia.SRBaseDatos.consultarTotalCuerposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTotalCuerpos", ReplyAction="*")]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.consultarTotalCuerposResponse> consultarTotalCuerposAsync(Astronomia.SRBaseDatos.consultarTotalCuerposRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Astronomia.SRBaseDatos.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Astronomia.SRBaseDatos.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCuerpoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCuerpo", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.InsertarCuerpoRequestBody Body;
        
        public InsertarCuerpoRequest() {
        }
        
        public InsertarCuerpoRequest(Astronomia.SRBaseDatos.InsertarCuerpoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCuerpoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descubridor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] archivo;
        
        public InsertarCuerpoRequestBody() {
        }
        
        public InsertarCuerpoRequestBody(string nombre, string descubridor, byte[] archivo) {
            this.nombre = nombre;
            this.descubridor = descubridor;
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCuerpoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCuerpoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.InsertarCuerpoResponseBody Body;
        
        public InsertarCuerpoResponse() {
        }
        
        public InsertarCuerpoResponse(Astronomia.SRBaseDatos.InsertarCuerpoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCuerpoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarCuerpoResult;
        
        public InsertarCuerpoResponseBody() {
        }
        
        public InsertarCuerpoResponseBody(string InsertarCuerpoResult) {
            this.InsertarCuerpoResult = InsertarCuerpoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTipo", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.insertarTipoRequestBody Body;
        
        public insertarTipoRequest() {
        }
        
        public insertarTipoRequest(Astronomia.SRBaseDatos.insertarTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        public insertarTipoRequestBody() {
        }
        
        public insertarTipoRequestBody(string descripcion) {
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.insertarTipoResponseBody Body;
        
        public insertarTipoResponse() {
        }
        
        public insertarTipoResponse(Astronomia.SRBaseDatos.insertarTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertarTipoResult;
        
        public insertarTipoResponseBody() {
        }
        
        public insertarTipoResponseBody(string insertarTipoResult) {
            this.insertarTipoResult = insertarTipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCuerposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCuerpos", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.ConsultaCuerposRequestBody Body;
        
        public ConsultaCuerposRequest() {
        }
        
        public ConsultaCuerposRequest(Astronomia.SRBaseDatos.ConsultaCuerposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultaCuerposRequestBody {
        
        public ConsultaCuerposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCuerposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCuerposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.ConsultaCuerposResponseBody Body;
        
        public ConsultaCuerposResponse() {
        }
        
        public ConsultaCuerposResponse(Astronomia.SRBaseDatos.ConsultaCuerposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaCuerposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultaCuerposResult;
        
        public ConsultaCuerposResponseBody() {
        }
        
        public ConsultaCuerposResponseBody(string ConsultaCuerposResult) {
            this.ConsultaCuerposResult = ConsultaCuerposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarTipos", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.consultarTiposRequestBody Body;
        
        public consultarTiposRequest() {
        }
        
        public consultarTiposRequest(Astronomia.SRBaseDatos.consultarTiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarTiposRequestBody {
        
        public consultarTiposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarTiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.consultarTiposResponseBody Body;
        
        public consultarTiposResponse() {
        }
        
        public consultarTiposResponse(Astronomia.SRBaseDatos.consultarTiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarTiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarTiposResult;
        
        public consultarTiposResponseBody() {
        }
        
        public consultarTiposResponseBody(string consultarTiposResult) {
            this.consultarTiposResult = consultarTiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAsociadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAsociados", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.InsertarAsociadosRequestBody Body;
        
        public InsertarAsociadosRequest() {
        }
        
        public InsertarAsociadosRequest(Astronomia.SRBaseDatos.InsertarAsociadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAsociadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCuerpo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idAsociado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idtipo;
        
        public InsertarAsociadosRequestBody() {
        }
        
        public InsertarAsociadosRequestBody(int idCuerpo, int idAsociado, int idtipo) {
            this.idCuerpo = idCuerpo;
            this.idAsociado = idAsociado;
            this.idtipo = idtipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAsociadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAsociadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.InsertarAsociadosResponseBody Body;
        
        public InsertarAsociadosResponse() {
        }
        
        public InsertarAsociadosResponse(Astronomia.SRBaseDatos.InsertarAsociadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAsociadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarAsociadosResult;
        
        public InsertarAsociadosResponseBody() {
        }
        
        public InsertarAsociadosResponseBody(string InsertarAsociadosResult) {
            this.InsertarAsociadosResult = InsertarAsociadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTotalCuerposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarTotalCuerpos", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.consultarTotalCuerposRequestBody Body;
        
        public consultarTotalCuerposRequest() {
        }
        
        public consultarTotalCuerposRequest(Astronomia.SRBaseDatos.consultarTotalCuerposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarTotalCuerposRequestBody {
        
        public consultarTotalCuerposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTotalCuerposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarTotalCuerposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Astronomia.SRBaseDatos.consultarTotalCuerposResponseBody Body;
        
        public consultarTotalCuerposResponse() {
        }
        
        public consultarTotalCuerposResponse(Astronomia.SRBaseDatos.consultarTotalCuerposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarTotalCuerposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarTotalCuerposResult;
        
        public consultarTotalCuerposResponseBody() {
        }
        
        public consultarTotalCuerposResponseBody(string consultarTotalCuerposResult) {
            this.consultarTotalCuerposResult = consultarTotalCuerposResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaseDatosSoapChannel : Astronomia.SRBaseDatos.BaseDatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaseDatosSoapClient : System.ServiceModel.ClientBase<Astronomia.SRBaseDatos.BaseDatosSoap>, Astronomia.SRBaseDatos.BaseDatosSoap {
        
        public BaseDatosSoapClient() {
        }
        
        public BaseDatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaseDatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseDatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseDatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRBaseDatos.HelloWorldResponse Astronomia.SRBaseDatos.BaseDatosSoap.HelloWorld(Astronomia.SRBaseDatos.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Astronomia.SRBaseDatos.HelloWorldRequest inValue = new Astronomia.SRBaseDatos.HelloWorldRequest();
            inValue.Body = new Astronomia.SRBaseDatos.HelloWorldRequestBody();
            Astronomia.SRBaseDatos.HelloWorldResponse retVal = ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.HelloWorldResponse> Astronomia.SRBaseDatos.BaseDatosSoap.HelloWorldAsync(Astronomia.SRBaseDatos.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRBaseDatos.HelloWorldResponse> HelloWorldAsync() {
            Astronomia.SRBaseDatos.HelloWorldRequest inValue = new Astronomia.SRBaseDatos.HelloWorldRequest();
            inValue.Body = new Astronomia.SRBaseDatos.HelloWorldRequestBody();
            return ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRBaseDatos.InsertarCuerpoResponse Astronomia.SRBaseDatos.BaseDatosSoap.InsertarCuerpo(Astronomia.SRBaseDatos.InsertarCuerpoRequest request) {
            return base.Channel.InsertarCuerpo(request);
        }
        
        public string InsertarCuerpo(string nombre, string descubridor, byte[] archivo) {
            Astronomia.SRBaseDatos.InsertarCuerpoRequest inValue = new Astronomia.SRBaseDatos.InsertarCuerpoRequest();
            inValue.Body = new Astronomia.SRBaseDatos.InsertarCuerpoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descubridor = descubridor;
            inValue.Body.archivo = archivo;
            Astronomia.SRBaseDatos.InsertarCuerpoResponse retVal = ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).InsertarCuerpo(inValue);
            return retVal.Body.InsertarCuerpoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.InsertarCuerpoResponse> Astronomia.SRBaseDatos.BaseDatosSoap.InsertarCuerpoAsync(Astronomia.SRBaseDatos.InsertarCuerpoRequest request) {
            return base.Channel.InsertarCuerpoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRBaseDatos.InsertarCuerpoResponse> InsertarCuerpoAsync(string nombre, string descubridor, byte[] archivo) {
            Astronomia.SRBaseDatos.InsertarCuerpoRequest inValue = new Astronomia.SRBaseDatos.InsertarCuerpoRequest();
            inValue.Body = new Astronomia.SRBaseDatos.InsertarCuerpoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descubridor = descubridor;
            inValue.Body.archivo = archivo;
            return ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).InsertarCuerpoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRBaseDatos.insertarTipoResponse Astronomia.SRBaseDatos.BaseDatosSoap.insertarTipo(Astronomia.SRBaseDatos.insertarTipoRequest request) {
            return base.Channel.insertarTipo(request);
        }
        
        public string insertarTipo(string descripcion) {
            Astronomia.SRBaseDatos.insertarTipoRequest inValue = new Astronomia.SRBaseDatos.insertarTipoRequest();
            inValue.Body = new Astronomia.SRBaseDatos.insertarTipoRequestBody();
            inValue.Body.descripcion = descripcion;
            Astronomia.SRBaseDatos.insertarTipoResponse retVal = ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).insertarTipo(inValue);
            return retVal.Body.insertarTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.insertarTipoResponse> Astronomia.SRBaseDatos.BaseDatosSoap.insertarTipoAsync(Astronomia.SRBaseDatos.insertarTipoRequest request) {
            return base.Channel.insertarTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRBaseDatos.insertarTipoResponse> insertarTipoAsync(string descripcion) {
            Astronomia.SRBaseDatos.insertarTipoRequest inValue = new Astronomia.SRBaseDatos.insertarTipoRequest();
            inValue.Body = new Astronomia.SRBaseDatos.insertarTipoRequestBody();
            inValue.Body.descripcion = descripcion;
            return ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).insertarTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRBaseDatos.ConsultaCuerposResponse Astronomia.SRBaseDatos.BaseDatosSoap.ConsultaCuerpos(Astronomia.SRBaseDatos.ConsultaCuerposRequest request) {
            return base.Channel.ConsultaCuerpos(request);
        }
        
        public string ConsultaCuerpos() {
            Astronomia.SRBaseDatos.ConsultaCuerposRequest inValue = new Astronomia.SRBaseDatos.ConsultaCuerposRequest();
            inValue.Body = new Astronomia.SRBaseDatos.ConsultaCuerposRequestBody();
            Astronomia.SRBaseDatos.ConsultaCuerposResponse retVal = ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).ConsultaCuerpos(inValue);
            return retVal.Body.ConsultaCuerposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.ConsultaCuerposResponse> Astronomia.SRBaseDatos.BaseDatosSoap.ConsultaCuerposAsync(Astronomia.SRBaseDatos.ConsultaCuerposRequest request) {
            return base.Channel.ConsultaCuerposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRBaseDatos.ConsultaCuerposResponse> ConsultaCuerposAsync() {
            Astronomia.SRBaseDatos.ConsultaCuerposRequest inValue = new Astronomia.SRBaseDatos.ConsultaCuerposRequest();
            inValue.Body = new Astronomia.SRBaseDatos.ConsultaCuerposRequestBody();
            return ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).ConsultaCuerposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRBaseDatos.consultarTiposResponse Astronomia.SRBaseDatos.BaseDatosSoap.consultarTipos(Astronomia.SRBaseDatos.consultarTiposRequest request) {
            return base.Channel.consultarTipos(request);
        }
        
        public string consultarTipos() {
            Astronomia.SRBaseDatos.consultarTiposRequest inValue = new Astronomia.SRBaseDatos.consultarTiposRequest();
            inValue.Body = new Astronomia.SRBaseDatos.consultarTiposRequestBody();
            Astronomia.SRBaseDatos.consultarTiposResponse retVal = ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).consultarTipos(inValue);
            return retVal.Body.consultarTiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.consultarTiposResponse> Astronomia.SRBaseDatos.BaseDatosSoap.consultarTiposAsync(Astronomia.SRBaseDatos.consultarTiposRequest request) {
            return base.Channel.consultarTiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRBaseDatos.consultarTiposResponse> consultarTiposAsync() {
            Astronomia.SRBaseDatos.consultarTiposRequest inValue = new Astronomia.SRBaseDatos.consultarTiposRequest();
            inValue.Body = new Astronomia.SRBaseDatos.consultarTiposRequestBody();
            return ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).consultarTiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRBaseDatos.InsertarAsociadosResponse Astronomia.SRBaseDatos.BaseDatosSoap.InsertarAsociados(Astronomia.SRBaseDatos.InsertarAsociadosRequest request) {
            return base.Channel.InsertarAsociados(request);
        }
        
        public string InsertarAsociados(int idCuerpo, int idAsociado, int idtipo) {
            Astronomia.SRBaseDatos.InsertarAsociadosRequest inValue = new Astronomia.SRBaseDatos.InsertarAsociadosRequest();
            inValue.Body = new Astronomia.SRBaseDatos.InsertarAsociadosRequestBody();
            inValue.Body.idCuerpo = idCuerpo;
            inValue.Body.idAsociado = idAsociado;
            inValue.Body.idtipo = idtipo;
            Astronomia.SRBaseDatos.InsertarAsociadosResponse retVal = ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).InsertarAsociados(inValue);
            return retVal.Body.InsertarAsociadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.InsertarAsociadosResponse> Astronomia.SRBaseDatos.BaseDatosSoap.InsertarAsociadosAsync(Astronomia.SRBaseDatos.InsertarAsociadosRequest request) {
            return base.Channel.InsertarAsociadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRBaseDatos.InsertarAsociadosResponse> InsertarAsociadosAsync(int idCuerpo, int idAsociado, int idtipo) {
            Astronomia.SRBaseDatos.InsertarAsociadosRequest inValue = new Astronomia.SRBaseDatos.InsertarAsociadosRequest();
            inValue.Body = new Astronomia.SRBaseDatos.InsertarAsociadosRequestBody();
            inValue.Body.idCuerpo = idCuerpo;
            inValue.Body.idAsociado = idAsociado;
            inValue.Body.idtipo = idtipo;
            return ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).InsertarAsociadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Astronomia.SRBaseDatos.consultarTotalCuerposResponse Astronomia.SRBaseDatos.BaseDatosSoap.consultarTotalCuerpos(Astronomia.SRBaseDatos.consultarTotalCuerposRequest request) {
            return base.Channel.consultarTotalCuerpos(request);
        }
        
        public string consultarTotalCuerpos() {
            Astronomia.SRBaseDatos.consultarTotalCuerposRequest inValue = new Astronomia.SRBaseDatos.consultarTotalCuerposRequest();
            inValue.Body = new Astronomia.SRBaseDatos.consultarTotalCuerposRequestBody();
            Astronomia.SRBaseDatos.consultarTotalCuerposResponse retVal = ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).consultarTotalCuerpos(inValue);
            return retVal.Body.consultarTotalCuerposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Astronomia.SRBaseDatos.consultarTotalCuerposResponse> Astronomia.SRBaseDatos.BaseDatosSoap.consultarTotalCuerposAsync(Astronomia.SRBaseDatos.consultarTotalCuerposRequest request) {
            return base.Channel.consultarTotalCuerposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Astronomia.SRBaseDatos.consultarTotalCuerposResponse> consultarTotalCuerposAsync() {
            Astronomia.SRBaseDatos.consultarTotalCuerposRequest inValue = new Astronomia.SRBaseDatos.consultarTotalCuerposRequest();
            inValue.Body = new Astronomia.SRBaseDatos.consultarTotalCuerposRequestBody();
            return ((Astronomia.SRBaseDatos.BaseDatosSoap)(this)).consultarTotalCuerposAsync(inValue);
        }
    }
}
